#!/bin/bash

echo "🚀 Headliner Performance Baseline Measurement"
echo "============================================"
echo "Date: $(date)"
echo "Branch: $(git branch --show-current)"
echo "Commit: $(git rev-parse --short HEAD)"
echo ""

echo "📋 Manual Testing Checklist:"
echo ""
echo "1. 🧠 MEMORY USAGE:"
echo "   - Launch /Applications/Headliner.app"
echo "   - Open Activity Monitor → All Processes"
echo "   - Find 'Headliner' process"
echo "   - Record Memory column value:"
echo "   Startup Memory: _____ MB"
echo ""
echo "2. 🎥 CAMERA PERFORMANCE:"
echo "   - Click menu bar icon"
echo "   - Time camera list appearance: _____ ms"
echo "   - Select different camera"
echo "   - Time until preview updates: _____ ms"
echo "   - Record peak memory after camera active: _____ MB"
echo ""
echo "3. 🔧 EXTENSION STATUS:"
echo "   - Check extension status update time: _____ ms"
echo "   - Open Console.app to check polling frequency"
echo ""
echo "4. ⏱️ APP LAUNCH:"
echo "   - Quit app completely"
echo "   - Time from launch to menu bar appearing: _____ seconds"
echo ""

read -p "Press Enter when measurements are complete..."

echo ""
echo "✅ Baseline captured! You can now:"
echo "   1. Fill in PERFORMANCE_BASELINE.md with your measurements"
echo "   2. git add PERFORMANCE_BASELINE.md && git commit -m 'Add baseline measurements'"
echo "   3. Switch back to migration branch: git checkout optimize/appstate-performance"
echo "   4. Rebase with main: git rebase main"
echo ""